// 定数定義
const GIFT_PACK_POINTS = {
  NORMAL_CARD: 5,
  SALE_CARD: 15,
  THREE_COMPANIES: 20,
  EMPTY_HAND: 30,
  UNIQUE_COMPANIES: 10,
  ROTTEN_CARD_PENALTY: 50,
  HAVE_ROTTEN_PENALTY: 10,
} as const;

// 特殊効果を持つカードのID
const SPECIAL_CARD_IDS = [7, 24, 41, 50, 51, 52, 53, 60] as const;

// postBattle関連の定数
const POST_BATTLE_CONSTANTS = {
  WASTE_REDUCTION: 1,
  HUNGRY_REDUCTION: 40,
} as const;

export { GIFT_PACK_POINTS, SPECIAL_CARD_IDS, POST_BATTLE_CONSTANTS };
